steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/[PROJECT_ID]/my-flask-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/[PROJECT_ID]/my-flask-app']

# Authenticate kubectl with your GKE cluster
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials [CLUSTER_NAME] --zone [ZONE] --project [PROJECT_ID]

# Apply Kubernetes deployment and service configurations
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/deployment.yaml']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/service.yaml']

images:
- 'gcr.io/[PROJECT_ID]/my-flask-app'
